### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ascherbakhov** [ascherbakhov/game-session-service#4]
# TODO

- [ ] Separate the app and Celery into different containers/images
- [ ] Integration with Sentry for error tracking
- [ ] Improve exception handling
- [ ] Implement retries for cache updates, but handle carefully to avoid cache overwrites from different workers
- [ ] Fix configuration initialization for tests
- [ ] Increase test coverage (currently at 88%)
- [ ] Sqlite database is used for unit tests, maybe not the best option
- [ ] Refactor the authorization logic (currently poorly implemented)
